### ISSUE TITLE
Update neighbourhood records for previously imported markets

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#659]
The import of updated/new neighbourhood records in seven imported markets (New Orleans, Baltimore, Portland, San Diego, Denver, Helsinki, San Jose and Atlanta) caused outlying records to receive updated `wof:hierarchy` and `wof:belongsto` properties; this is due to the new locality shape covering these updated/new neighbourhood lat/longs.

A new round of PIP work is needed for these markets to take care of any erroneous records that gained new (incorrect) `wof:hierarchy` and `wof:belongsto` property values.

- [x] New Orleans
- [x] Baltimore
- [x] Portland
- [x] San Diego
- [x] Denver
- [x] Helsinki
- [x] San Jose
- [x] Atlanta
- [x] Oakland

**Comment by stepps00** [comment]
Files are in S3 (`misc`/`Issue 659`). Includes the same file convention and properties as previous neighbourhood files.

@thisisaaronland - assigning this issue to myself; this may be a good first test when I use the new PIP tools.

**Comment by thisisaaronland** [comment]
@stepps00 - various parse errors, trying to import this:

Baltimore

```
INFO:root:process /usr/local/data/whosonfirst-work/issue-659/Baltimore_20170216/cessation.geojson
process name (wof:name) = Westgate
process superseded_by (wof:superseded_by) = 85870095
process is_current (mz:is_current) = 0
process deprecated (edtf:deprecated) = None
process cessation (edtf:cessation) = 2017-02-16
process mz_note (mz:note) = None
process id (wof:id) = 1108795085
INFO:root:{u'edtf:cessation': u'2017-02-16', 'wof:repo': 'whosonfirst-data', u'wof:name': u'Westgate', u'wof:superseded_by': [85870095], u'mz:is_current': u'0', u'wof:id': 1108795085}
process name (wof:name) = Belgravia
process superseded_by (wof:superseded_by) = (0:)
Traceback (most recent call last):
  File "./neighbourhoods.py", line 461, in <module>
    print imp.process()
  File "./neighbourhoods.py", line 35, in process
    self.retired.process()
  File "./neighbourhoods.py", line 382, in process
    prepped = self.aliases.prep(props)
  File "/usr/local/acope/whosonfirst-toolbox/scripts/neighbourhood-tool/properties.py", line 70, in prep
    v = map(int, v.split(","))
ValueError: invalid literal for int() with base 10: '(0:)'
```

Helsinki

```
INEN', u'rev_lat': 60.1990133945521}
INFO:root:alt props for 890537227 would be {'src:geom': u'hkigis', 'wof:placetype': u'macrohood', 'wof:id': 890537227}
INFO:root:existing props for 890537227 would be {u'src:lbl:centroid': u'mapshaper', u'geom:longitude': 25.038591, u'name:swe_x_preferred': [u'Herton\xe4s'], u'wof:tags': [], u'mz:max_zoom': 15, u'wof:country': u'FI', u'fsgov:ajo_pvm': u'2015/03/31', u'lbl:latitude': 60.199013, u'wof:hierarchy': [{u'region_id': 85683067, u'continent_id': 102191581, u'macrohood_id': 890537227, u'localadmin_id': 907199715, u'country_id': 85633143, u'macroregion_id': 404227411, u'locality_id': 101748417, u'empire_id': 136253047, u'borough_id': 890536883}], u'mz:hierarchy_label': 1, u'iso:country': u'FI', 'src:geom_alt': [u'hkigis'], u'wof:geomhash': u'9be385a3180594a7145e982e8df00dea', u'wof:name': u'Herttoniemi', u'src:geom': u'hkigis', u'name:fin_x_preferred': [u'Herttoniemi'], u'fsgov:Kunta': u'091', u'wof:id': 890537227, u'mz:min_zoom': 13, u'wof:repo': u'whosonfirst-data', u'wof:breaches': [], u'lbl:longitude': 25.038021, u'wof:supersedes': [], u'fsgov:nimi': u'HERTTONIEMI', u'geom:area': 0.001229, u'edtf:inception': u'uuuu', u'fsgov:Aluejako': u'KAUPUNGINOSA', u'geom:bbox': u'25.0068041549,60.1830772357,25.0764833343,60.2193429544', u'geom:latitude': 60.199946, u'geom:area_square_m': 7550236.439521, u'edtf:cessation': u'uuuu', u'wof:belongsto': [85683067, 102191581, 907199715, 85633143, 404227411, 101748417, 136253047, 890536883], u'wof:placetype': u'macrohood', u'fsgov:nimi_se': u'HERTON\xc4S', u'wof:lastmodified': 1485376644, u'wof:superseded_by': [], u'fsgov:Tunnus': u'43', u'wof:parent_id': 890536883}
Traceback (most recent call last):
  File "./neighbourhoods.py", line 461, in <module>
    print imp.process()
  File "./neighbourhoods.py", line 40, in process
    updated = self._update(updated, self.existing.process(rel))
  File "./neighbourhoods.py", line 292, in process
    prepped = self.aliases.prep(new_props)
  File "/usr/local/acope/whosonfirst-toolbox/scripts/neighbourhood-tool/properties.py", line 43, in prep
    a = self.foo(k)
  File "/usr/local/acope/whosonfirst-toolbox/scripts/neighbourhood-tool/properties.py", line 33, in foo
    raise Exception, "Unknown key %s" % k
Exception: Unknown key hkigis:SUURP_TN
```

Oakland

```
process id (wof:id) = 1108794093
process rev_lat (reversegeo:latitude) = 37.807704
process name (wof:name) = Central Oakland
INFO:root:prepped props are {u'mz:min_zoom': 13, u'name:eng_x_variant': [u'C Oakland'], 'wof:repo': 'whosonfirst-data', u'iso:country': u'US', u'mz:is_landuse_aoi': 0, u'lbl:longitude': -122.265323, u'wof:country': u'US', u'wof:name': u'Central Oakland', u'mz:is_funky': 0, u'mz:max_zoom': 15, u'reversegeo:longitude': -122.265323, u'wof:placetype': u'macrohood', u'wof:supersedes': [], u'src:geom': u'mz', u'wof:id': 1108794093, u'lbl:latitude': 37.807704, u'reversegeo:latitude': 37.807704, u'wof:parent_id': 85921881}
INFO:root:process /usr/local/data/whosonfirst-work/issue-659/Oakland_20170306/wof_neighbourhoods.geojson
Traceback (most recent call last):
  File "./neighbourhoods.py", line 461, in <module>
    print imp.process()
  File "./neighbourhoods.py", line 40, in process
    updated = self._update(updated, self.existing.process(rel))
  File "./neighbourhoods.py", line 280, in process
    col = json.load(fh)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 58 column 457 (char 147491)
```

San Diego

```
process cessation (edtf:cessation) = 2017-02-15
process mz_note (mz:note) = None
process id (wof:id) = 1108802155
INFO:root:{u'edtf:cessation': u'2017-02-15', 'wof:repo': 'whosonfirst-data', u'wof:name': u'Shelltown', u'wof:superseded_by': [85867419], u'mz:is_current': u'0', u'wof:id': 1108802155}
INFO:root:process /usr/local/data/whosonfirst-work/issue-659/SanDiego_20170215/deprecated.geojson
process name (wof:name) = Cypress Greens
process deprecated (edtf:deprecated) = 2017-02-15
process is_current (mz:is_current) = 0
process superseded_by (wof:superseded_by) = (0:)
Traceback (most recent call last):
  File "./neighbourhoods.py", line 461, in <module>
    print imp.process()
  File "./neighbourhoods.py", line 35, in process
    self.retired.process()
  File "./neighbourhoods.py", line 382, in process
    prepped = self.aliases.prep(props)
  File "/usr/local/acope/whosonfirst-toolbox/scripts/neighbourhood-tool/properties.py", line 70, in prep
    v = map(int, v.split(","))
ValueError: invalid literal for int() with base 10: '(0:)'
```

San Jose

```
INFO:root:prepped props are {u'mz:min_zoom': 13, 'wof:repo': 'whosonfirst-data', u'iso:country': u'US', u'mz:is_landuse_aoi': 0, u'lbl:longitude': -121.894751, u'wof:supersedes': [85882407], u'wof:name': u'Central San Jose', u'mz:is_funky': 0, u'mz:max_zoom': 15, u'reversegeo:longitude': -121.894751, u'wof:placetype': u'macrohood', u'wof:country': u'US', u'src:geom': u'mz', u'lbl:latitude': 37.299284, u'reversegeo:latitude': 37.299284, u'wof:id': 1108782557}
INFO:root:new props is {u'src_geom': u'mz', u'lbl_longitude': -121.86404, u'placetype': u'macrohood', u'rev_long': -121.86404, u'lbl_latitude': 37.22073, u'is_landuse_aoi': 0, u'max_zoom': 16, u'is_funky': 0, u'iso_country': u'US', u'wof_country': u'US', u'supersedes': u'85869071', u'min_zoom': 13, u'eng_variant_name': u'Almaden Vly, Almaden', u'id': 1108827447, u'rev_lat': 37.22073, u'name': u'Almaden Valley'}
ERROR:root:unable to locate path for 1108827447 (/usr/local/data/whosonfirst-data/data)
Traceback (most recent call last):
  File "./neighbourhoods.py", line 461, in <module>
    print imp.process()
  File "./neighbourhoods.py", line 40, in process
    updated = self._update(updated, self.existing.process(rel))
  File "./neighbourhoods.py", line 289, in process
    existing_feature = mapzen.whosonfirst.utils.load(self.data, wofid)
  File "/usr/local/lib/python2.7/dist-packages/mapzen/whosonfirst/utils/__init__.py", line 113, in load
    raise Exception, "unable to locate path for %s (%s)" % (id, root)
Exception: unable to locate path for 1108827447 (/usr/local/data/whosonfirst-data/data)
```

**Comment by stepps00** [comment]
@thisisaaronland - these five conflicts should be taken care of, new files are in S3.

Baltimore - removed bunk `(0:)` values.
Helsinki - Added missing source alias properties (https://github.com/whosonfirst/whosonfirst-properties/commit/745f370de37aabb9f11249afae5fb5c6c1702257)
Oakland - Replaced source property `\` values with `/` values.
San Diego - Removed bunk `(0:)` values.
San Jose - File structure was incorrect. We now have a `no_wof_macrohood.geojson` file.

**Comment by stepps00** [comment]
Commits a8ee00f, e931c01, cb68886, 4d66e0b, and 1177454 were merged to `master`. Closing issue.
